# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.15.0
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
  deploy:
    docker:
      - image: cimg/node:22.15.0
    steps:
      - checkout
      - run: yarn
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: yarn build
      - run: yarn export
      - run: touch out/.nojekyll
      - run: yarn deploy:gh-pages
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
