import Head from "next/head";
import styles from "/styles/Home.module.css";
import CustomBar from "src/components/CustomBar";

export default function Home() {
  return (
    <div className={styles.container} style={{ width: "100vw", padding: 0 }}>
      <Head>
        <title>いろいろ置くページ</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={process.env.NEXT_PUBLIC_ASSET_PREFIX + "/favicon.ico"}
        />
      </Head>
      <CustomBar />
      <main className={styles.main}>
        <h1 className={styles.title}>右上のメニューボタンからどうぞ</h1>
      </main>
    </div>
  );
}
