import Head from "next/head";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>まだ何もありません</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={process.env.NEXT_PUBLIC_ASSET_PREFIX + "/favicon.ico"}
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ここは工事中です</h1>
      </main>
    </div>
  );
}
